# Generated by Django 3.1.1 on 2020-09-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
