# Generated by Django 3.1.1 on 2020-09-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_post_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
