# Generated by Django 3.1.1 on 2020-09-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20200927_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(max_length=3),
        ),
    ]
